### PR TITLE
[refactor] Use parcel bundler

### PR DESCRIPTION
**Pull request by SHA-2048**
The goal of these changes is the following:

- Move to using npm/parcel for a more standard dev environment.
- Split swap.riot into smaller sub-components. To reduce complexity by adding structure and ease future maintenance and developments

More work will certainly need to be carried out, but I'm opening the PR for first feedback as there are several changes.

There are also some improvements done revealed during refactoring:
- Removed fake background when token selector is opened (replaced it with an outside click event listener)
- Fixed Token ordering in token selection list. was not working when using filter value from input

### CODE REVIEW

**Comment by talegift** [comment]
It looks like this branch was forked from an old master which doesn't include the latest changes.

Can you merge master into this branch and resolve the conflicts?

**Comment by SHA-2048** [comment]
@talegift I've resolved merge conflicts with master. It was a bit more than a simple merge as I had to move last changes done by @nipa85 to fit into the new component structure.

I've noticed that the app load time got better after the refactoring. Mainly due to the fact token list and balance updates are now done asynchronously on the background.

I've tested a bit more, looks ok. But due to the amount of code change this is will be a rather difficult PR to review, sorry for that in advance.

**Comment by talegift** [comment]
@vfatouros Can you check if all of this still works and looks the same?

**Review by vfatouros — APPROVED** [review]
UI works as expected!

**Pull request merged**
