### PR TITLE
Implement 0x orders submit

### PR DESCRIPTION
**Pull request by SHA-2048**
Resolves issue #18 
Fixes issue #29 (regression due to mistakenly using WETH address when swapping ETH for X)
Resolves issue #28 

Orders to 0x are working now for ERC20 tokens. 

ETH cannot be used though as not supported by 0x (only WETH), so maybe we need to hide it from the token selector when using the limit order feature. This also means we cannot use as default input token as well.

Also the orders are submitted with no maker/taker/referal fee for now, so please tell me if this needs to be changed. Relevant code for this is in `src/common/0x_orders_proxy.js` I've put available options in comment.

When submitting a limit order, if the token allowance is not set to 0x ERC20 proxy contract, the user will be requested to issue an approve first, only then the place order button will appear.

The order book now is updated periodically, due to the fact there is an update when metric balance and eth balance is refreshed.
So when a limit order is submitted successfully it eventually shows up on the order book. Notice that it might not be immediate as 0x API takes some time to include the new order in the returned orders list.

0x javascript API seems pretty powerful and clean, it might be worth to use fully instead of relying on web3.js.

### CODE REVIEW

**Review by vfatouros — APPROVED** [review]
Functions as advertised, I was able to approve a token and place a swap, which showed up in the order book.

**Comment by talegift** [comment]
Some of the icons are not loading at all https://share.getcloudapp.com/NQu1lAWm - cETH for example

And other icons sometimes load up very large res images with almost 1MB in size! Such as this https://zapper.fi/images/DOUGH-icon.png

I suggest switching back to some token list which has links to all small icons.

**Comment by talegift** [comment]
When the value is 0, it shouldn't show any USD estimate (see output field):

https://share.getcloudapp.com/DOu9dEL0

**Comment by vfatouros** [comment]
Not sure there is a better alternative, at least not readily available. We
could rehost the assets maybe and fix the errant ones, or wait for Zapper
to fix them.

Trustwallet has a lot of token logos but no list that I can see
https://github.com/trustwallet/assets/tree/master/blockchains/ethereum/assets

**Comment by SHA-2048** [comment]
@talegift I've fixed the `0` price display issue.

For the logo size one, the image transfer sizes are small as they are compressed. for example the DOUGH one transfers 47B on the network whereas the image weight is 750KB. So it does not seem to affect load time significantly IMO.

For the ones not found I can try if we can put a default image when that happens. Like the one we use for tokens added with their address.

**Comment by SHA-2048** [comment]
@talegift Added a defaut token logo image when fetch query fails. Gives this:

image

**Pull request merged**
