### PR TITLE
[feature] Support token Urls

### LINKED ISSUE #48: Token urls
Use fragment to select an input token

Format: http://metric.exchange/#/token_address

E.g. http://metric.exchange/#/0x6e36556b3ee5aa28def2a8ec3dae30ec2b208739 should select BUILD

The current URL should also change when the user selects another token.

This will allow us to send links to specific markets.

### PR DESCRIPTION
**Pull request by SHA-2048**
Resolves #48

### CODE REVIEW

**Comment by talegift** [comment]
```
order_dashboard.riot:27 Uncaught (in promise) TypeError: Cannot read property 'toLowerCase' of undefined
    at order_dashboard.riot:27
    at Array.find (<anonymous>)
    at Object.inputTokenAvailable (order_dashboard.riot:27)
    at Object.evaluate (order_dashboard.riot:49)
    at Object.update (riot.esm.js:799)
    at Object.mount (riot.esm.js:795)
    at riot.esm.js:1661
    at Array.forEach (<anonymous>)
    at Object.mount (riot.esm.js:1661)
    at Object.mount (riot.esm.js:2425)
```

https://share.getcloudapp.com/Z4uy8LlK

Clicking on connect wallet didn't help.

**Comment by SHA-2048** [comment]
> ```
> order_dashboard.riot:27 Uncaught (in promise) TypeError: Cannot read property 'toLowerCase' of undefined
>     at order_dashboard.riot:27
>     at Array.find (<anonymous>)
>     at Object.inputTokenAvailable (order_dashboard.riot:27)
>     at Object.evaluate (order_dashboard.riot:49)
>     at Object.update (riot.esm.js:799)
>     at Object.mount (riot.esm.js:795)
>     at riot.esm.js:1661
>     at Array.forEach (<anonymous>)
>     at Object.mount (riot.esm.js:1661)
>     at Object.mount (riot.esm.js:2425)
> ```
> 
> https://share.getcloudapp.com/Z4uy8LlK
> 
> Clicking on connect wallet didn't help.

@talegift Can you try again now? I did not have the issue on my local build.

**Comment by talegift** [comment]
Still same

**Comment by talegift** [comment]
@vfatouros can you verify?

**Comment by SHA-2048** [comment]
> Still same

@talegift 

I had to upgarde to latest version of riot, so maybe it is failing for that reason. Can you clean dist and possibly project node_modules folders and try again ?

**Review by vfatouros — APPROVED** [review]
The feature works for me (http://localhost:1234/#/0x6e36556b3ee5aa28def2a8ec3dae30ec2b208739 opens the Build page), after using `npm install` (wouldn't compile before).

**Pull request merged**
