### PR TITLE
[feature] Support limit orders between any pair of ERC20 Tokens

### LINKED ISSUE #54: Introduce output token selector
Having been thinking about specific places Metric could be used, it seems necessary to have the ability to select both input and output tokens.

For example, this would allow us to:
- Buy BUILD directly with ETH without the buyer needing to first sell their ETH
- Sell CPOOL directly to ESD and vice-versa (http://esd.money/)

UI should look like this: https://share.getcloudapp.com/L1uQ1mQQ

This PR should also support market URLs: http://metric.exchange/#/input_token/output_token

### PR DESCRIPTION
**Pull request by SHA-2048**
Resolves #54 

- ETH cannot be part of the token list as 0x does not support it.
- For now only orders with DAI as output token will have the `>10 DAI` check. To see have the same for any token

### CODE REVIEW

**Comment by talegift** [comment]
Needs conflict resolution

**Comment by talegift** [comment]
There is also a very large gap under the buttons: https://share.getcloudapp.com/ApuL5JL7

Can we make it look like in the design? https://share.getcloudapp.com/L1uQ1mQQ

**Comment by SHA-2048** [comment]
> There is also a very large gap under the buttons: https://share.getcloudapp.com/ApuL5JL7
> 
> Can we make it look like in the design? https://share.getcloudapp.com/L1uQ1mQQ

Changed layout as per design

**Comment by talegift** [comment]
Pasting a custom token address doesn't seem to work in the output token selector.

**Comment by SHA-2048** [comment]
> Pasting a custom token address doesn't seem to work in the output token selector.

@talegift Have tested after merging with master branch or before. a token list refresh issue was fixed by one of the other PRs. I've tried with bCRED address on output token and it showed. Can you try again ? or give me the token address you tested with ?

**Comment by talegift** [comment]
Interesting. Looks like it's working now. Maybe it was some cashing issue.

But there is another issue now.

Following token pair shows "Infinity" in the order book.

http://localhost:1234/#/0x36f3fd68e7325a35eb768f1aedaae9ea0689d723/0x989a1b51681110fe01548c83b37258fc9e5dfd0e

https://share.getcloudapp.com/OAuJYZ1B

**Comment by SHA-2048** [comment]
> Interesting. Looks like it's working now. Maybe it was some cashing issue.
> 
> But there is another issue now.
> 
> Following token pair shows "Infinity" in the order book.
> 
> http://localhost:1234/#/0x36f3fd68e7325a35eb768f1aedaae9ea0689d723/0x989a1b51681110fe01548c83b37258fc9e5dfd0e
> 
> https://share.getcloudapp.com/OAuJYZ1B

CPOOL is not indexed by CoinGecko, so it returns nothing when it request for a price. By default I was using 0 as a price in this case. Changed it to `NaN`

**Pull request merged**
