### PR TITLE
Add order book using 0x API

### LINKED ISSUE #13: Use 0x API to fetch the orders
Design: https://www.figma.com/file/E2j6e6tcbjmraEjhupg32a/Metric?node-id=197%3A19

Use 0x API to display orders of the selected token pair https://0x.org/docs/api#get-srav3orderbook

This task is only to fetch and display the orderbook. Order creation and filling will be a part of another task.

Also please notice the top navigation switcher (Quick swap / Limit orders). Which is a part of this task.

### PR DESCRIPTION
**Pull request by SHA-2048**
resolves #13 

I made the PR mainly to share the status and have quick feedback.

I'm still not sure about the price/volume calculations. There some weird prices that appear in the order book and I'm not sure if these are real ones or there is a mistake in the calculation.

I had to re-work the page layout to make the new content fit correctly.
 - Switched to using CSS grid layouts
 - the header links are now hidden on small screens as they overlap with the connected address

Scroll bar color is not good, so I'll update the PR to correct it.

### CODE REVIEW

**Comment by SHA-2048** [comment]
All layout stuff is finished now. 

There is only one call to the 0x API with max 50 orders (bids + asks). This could be improved to get more data. Please tell me it is needed.

**Comment by talegift** [comment]
Looks great!

**Comment by talegift** [comment]
Can we add a check and remove the top nav "swap / limit" if the URL contains "metric.exchange"

Since the feature is not finished yet.

**Comment by SHA-2048** [comment]
@talegift I've added the condition to display order book links only when url host is different from 'metric.exchange'

**Comment by vfatouros** [comment]
PR complete from what I see

**Comment by talegift** [comment]
Looks like this PR breaks some of the styling.

- position of the logo and top nav
- position of the bottom social links
- margins of various elements

The design should stay as it is right now on http://metric.exchange/

Can you compare it with http://metric.exchange/ and change back what is different?

**Comment by SHA-2048** [comment]
> Looks like this PR breaks some of the styling.
> 
> * position of the logo and top nav
> * position of the bottom social links
> * margins of various elements
> * position of the swap form
> * and more
> 
> The design should stay as it is right now on http://metric.exchange/
> 
> Can you compare it with http://metric.exchange/ and change back what is different?

Yes will do it. For the links at the bottom, they broke when we display the order book. I had to change them so they are pushed down when order book appears. Is it possible to place them somewhere else ?

**Pull request merged**
