### PR TITLE
Add Theme switch capability

### LINKED ISSUE #7: Add light mode
Add light mode to the settings toggle. Feel free to decide on the color scheme for the light mode.

### PR DESCRIPTION
**Pull request by SHA-2048**
fixes #7 

Rebased on PR #9 

Here is the list of behaviors implemented here:
- Default theme is dark
- Add a settings drop down on top right
- There is a slider inside the drop down. it is added to enable light mode (slider button color changes with theme)
- The user choice is memorized in local storage
- Changed switch button arrows color to make pop for both themes
- Add slight drop shadow to the logo and made slightly bigger to avoid pixelated shadows

preview of the light mode:
Screen Shot 2020-10-04 at 19 28 28

preview dark mode:
Screen Shot 2020-10-04 at 19 28 58

### CODE REVIEW

**Comment by talegift** [comment]
@mlahia I've invited you to the repo. Feel free to make the PRs directly in this project (instead of forks). It makes it easier to review locally.

**Comment by talegift** [comment]
Thanks for the contribution!

I believe the color scheme of this light mode needs more work as the only thing that changes here is the background color set to pure white.

- Top navigation is unreadable as it's still white
- logo has unpleasant black borders
- light green of the button has a very low contract, making it difficult to read
- etc

When checking the theme, we need the colors of all elements instead of switching only the background to #fff.

Unfortunately, I currently don't have the time to design the white theme as I'm focusing on other issues. Unless this is changed to something more pleasing, this PR can't be merged at this point.

**Comment by mlahia** [comment]
The light theme background is not flat white. maybe there is an issue with the screenshot. Think are fine now I did fix them. Other colors have changed as well. I've made two color pallets in the style.css file for both themes, I will try to adjust them more...

**Comment by talegift** [comment]
Can you post a new screenshot?

**Comment by SHA-2048** [comment]
@talegift latest status:

image

and

image

**Comment by talegift** [comment]
I've made the design fo the light mode. Can we make it like this?

https://www.figma.com/file/E2j6e6tcbjmraEjhupg32a/Metric?node-id=163%3A0

When you sign up to Figma (it's free), it allows you to inspect all individual elements. Please follow all colors, sizes and element distances.

If this PR can match the design, I can merge it.

**Comment by SHA-2048** [comment]
OK, that will be a bit more work. There are more colors than current theme. Will base the changes on it.
I prefer though to wait for PR #9 to get merged to avoid dealing with merge conflicts

**Comment by SHA-2048** [comment]
closing PR and creating a new one from proper branch

**Pull request closed without merging**
